export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const ACTIVATE_USER_ACCOUNT = 'ACTIVATE_USER_ACCOUNT'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'

export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS'
export const UPDATE_AVATAR_ERROR = 'UPDATE_AVATAR_ERROR'
export const GET_AVATAR_SUCCESS = 'GET_AVATAR_SUCCESS'

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const INCREASE_SKIP = 'INCREASE_SKIP '
export const DECREASE_SKIP = 'DECREASE_SKIP '
export const RESET_SKIP = 'RESET_SKIP '

export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_ERROR = 'GET_SINGLE_USER_ERROR'

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'

export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS'
export const CREATE_REQUEST_ERROR = 'CREATE_REQUEST_ERROR'

export const SHOW_REQUEST_COMPONENT = 'SHOW_REQUEST_COMPONENT'
export const HIDE_REQUEST_COMPONENT = 'HIDE_REQUEST_COMPONENT'

export const CHANGE_FILTER = 'CHANGE_FILTER'
export const GET_REQUESTS_BEGIN = 'GET_REQUESTS_BEGIN'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'
export const GET_REQUESTS_ERROR = 'GET_REQUESTS_ERROR'

export const RESPONDE_REQUEST_SUCCESS = 'RESPONDE_REQUEST_SUCCESS'
export const RESPONDE_REQUEST_ERROR = 'RESPONDE_REQUEST_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

